# Generated by Django 4.0.5 on 2022-09-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoviews',
            old_name='topic',
            new_name='video',
        ),
    ]
