# Generated by Django 4.0.5 on 2022-09-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_topic_videoviews_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoviews',
            name='timeOfView',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
