# Generated by Django 4.0.5 on 2022-09-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
