# Generated by Django 4.0.5 on 2022-09-30 04:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_topicimage_alter_video_description2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
