# Generated by Django 4.0.5 on 2022-09-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_alter_video_description_alter_video_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='questionImage',
            field=models.ImageField(blank=True, upload_to='mcqImages/'),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
