# Generated by Django 4.0.5 on 2022-09-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_mcq_questionimage_alter_mcq_option3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='hint',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
