# Generated by Django 4.0.5 on 2022-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_video_sectionname'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='inOrder',
            field=models.BooleanField(default=True),
        ),
    ]
