# Generated by Django 4.0.5 on 2022-10-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_section_inorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='facultyCheck',
            field=models.BooleanField(default=False),
        ),
    ]
