# Generated by Django 4.0.5 on 2022-10-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_facultycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hideVideo',
            field=models.BooleanField(default=False),
        ),
    ]
