# Generated by Django 4.0.5 on 2022-10-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_alter_mcq_question_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='inTime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='outTime',
            field=models.DateTimeField(default=None),
        ),
    ]
