# Generated by Django 4.0.5 on 2022-10-12 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0021_alter_attendence_intime_alter_attendence_outtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoviews',
            name='faculty',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
