# Generated by Django 4.0.5 on 2022-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_videoviews_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='facultyCheck',
            field=models.BooleanField(default=False),
        ),
    ]
